## Basic Configuration
title = "Moien Tajik"
baseURL = "/"
languageCode = "en"
paginate = 10

## Hugo Built-in Features
disqusShortname = "moientajik"
googleAnalytics = "G-Y2XBPMY9EE"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  about="Moien Tajik is a principal software engineer with more than 8 years of experience in developing enterprise scalable applications."
  themeColor="theme-base-te"
  author = "Moien Tajik"
  description = "Principal Software Engineer"
  authorimage = "/img/Moien Tajik.png"
  dateformat = "01/02/2006"
  highlightjs = true
  highlightjsstyle = "atom-one-dark"
  
## Social Accounts
[params.social]
  twitter="MoienTajik"
  github="MoienTajik"
  linkedin="MoienTajik"
  stackoverflow="moientajik"
  email = "moientajik1@gmail.com"
  medium="MoienTajik"
  
## Main Menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Tags"
    weight = 300
    identifier = "tags"
    url = "/tags/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true